### ISSUE TITLE
Ionic 3 issue - adjustConfig.hasConversionValueUpdatedCallbackListener is not a function

### ISSUE THREAD

**Issue by afelipelli** [adjust/cordova_sdk#147] opened 2021-09-24 13:10 UTC
I implemented the SDK with the latest plugin and Ionic wrapper:

ionic cordova plugin add com.adjust.sdk
npm install @ionic-native/adjust

which installed these:

"com.adjust.sdk": "^4.29.0",
"@ionic-native/adjust": "^5.36.0",

With those in place, the attribution wasn't working. After debugging, I noticed this error in the logs:

TypeError: adjustConfig.hasConversionValueUpdatedCallbackListener is not a function
That was when I called adjust.create()

Indeed, this function didn't exist and I couldn't make it work, so I downgraded to versions I had used before:

"com.adjust.sdk": "^4.23.0",
"@ionic-native/adjust": "^5.29.0",

And that worked. So apparently, there's something wrong with the latest versions. Maybe the combination of these two versions don't work? Notice I don't call this hasConversionValueUpdatedCallbackListener in my code.

Thanks,
Alex

**Comment by uerceg** [comment] 2021-09-24 13:20
Hi @afelipelli 

Thanks for reporting this. We'll check this on our end and keep you posted.

**Comment by rahulm2** [comment] 2021-11-09 18:33
@afelipelli @uerceg when I moved back "com.adjust.sdk": "^4.23.0", "@ionic-native/adjust": "^5.29.0" it worked fine for android but didnt work for IOS. Can any of you help me with this

**Comment by IgorSavchenko90** [comment] 2021-11-22 11:28
Same problem. Have any solution?

**Comment by rahulm2** [comment] 2021-11-22 11:38
@afelipelli @uerceg Where can I find the documentation for ionic and capacitor implementation? Facing an issue with ios builds

**Comment by uerceg** [comment] 2021-12-02 15:40
Hey guys,

Sorry for delay on this one. I think I see where the issue is. JavaScript method which is mentioned in the error message (https://github.com/adjust/cordova_sdk/blob/master/www/adjust_config.js#L290-L292) is not added to `ionic-native` typings (missing from this section https://github.com/danielsogl/awesome-cordova-plugins/blob/master/src/%40awesome-cordova-plugins/plugins/adjust/index.ts#L220-L242). 

We will submit PR to `awesome-cordova-plugins` repo with the fix which, once merged should hopefully make this error disappear. Will keep you posted.

**Comment by uerceg** [comment] 2021-12-02 15:54
[PR](https://github.com/danielsogl/awesome-cordova-plugins/pull/3886) submitted.

**Comment by Aviho-M** [comment] 2021-12-27 07:19
Hi guys any new ?
Which Sdk version works best?

**Comment by uerceg** [comment] 2022-01-12 21:49
Hey @Aviho-M,

This is already released in `awesome-cordova-plugins` repo. If you are still facing the same issue, it might be because you are still trying to use TypeScript typings from deprecated `ionic-native` repo instead from `awesome-cordova-plugins`. Give this a shot:

1. Check if inside of your `APP_DIRECTORY/node_modules` you have `@ionic-native/adjust` folder. If you do, that means that you have install from `ionic-native` repo. Remove it with `npm uninstall @ionic-native/adjust`.
2. Install Adjust TypeScript typings from `awesome-cordova-plugins` repository with `npm install @awesome-cordova-plugins/adjust`.

After this, things should hopefully work. Let us know if this worked for you.

**Comment by uerceg** [comment] 2022-02-18 13:48
In case issue still persists for you, feel free to comment / reopen. Cheers.

**Closed by uerceg** 2022-02-18 13:48 UTC
