### ISSUE TITLE
Adjust.requestTrackingAuthorizationWithCompletionHandler causes app crash

### ISSUE THREAD

**Issue by fxc-dev** [adjust/cordova_sdk#119] opened 2020-09-07 05:38 UTC
Hello! We updated cordova plugin to version 4.23 and uncommented line for AppTrackingTransparency.framework.
We used **Xcode 12 beta 6** and installed app with updated plugin to iPhone 8 with **iOS 14 beta 7** and on every call of "requestTrackingAuthorizationWithCompletionHandler" method - application crashes:
![image](https://user-images.githubusercontent.com/24408933/92351818-d0004d80-f106-11ea-8fda-e691c3db3e20.png)
It happens right on [Adjust requestTrackingAuthorizationWithCompletionHandler] call in Objective-C, completionHandler in this method not fired
![image](https://user-images.githubusercontent.com/24408933/92351895-0047ec00-f107-11ea-8a2c-827388570aad.png)

Same happens on iOS 14 simulator

**Comment by ugi** [comment] 2020-09-11 22:21
Hi @fxc-dev 

Thanks for reporting. Do you see `AppTrackingTransparency.framework` being added to your resulting Xcode project? Also, can you paste in here code from your Cordova app where you're calling this method?

**Comment by fxc-dev** [comment] 2020-09-15 05:59
> Hi @fxc-dev
> 
> Thanks for reporting. Do you see `AppTrackingTransparency.framework` being added to your resulting Xcode project? Also, can you paste in here code from your Cordova app where you're calling this method?
> 
> Is there a possibility that callback you're passing to this method ends up being null-ed before it gets pinged by our SDK?

Yes, `AppTrackingTransparency.framework` inside Xcode project, if this framework not in project then nothing happend if we call "requestTrackingAuthorizationWithCompletionHandler"

We call this method like in plugin example
`Adjust.requestTrackingAuthorizationWithCompletionHandler(function(status) {
    switch (status) {
        case 0:
            // ATTrackingManagerAuthorizationStatusNotDetermined case
            break;
        case 1:
            // ATTrackingManagerAuthorizationStatusRestricted case
            break;
        case 2:
            // ATTrackingManagerAuthorizationStatusDenied case
            break;
        case 3:
            // ATTrackingManagerAuthorizationStatusAuthorized case
            break;
    }
});`

And with just console.log to test it
`Adjust.requestTrackingAuthorizationWithCompletionHandler(function(status) {
    console.log(status)
    }
});`

**Comment by ugi** [comment] 2020-09-29 21:19
Hi @fxc-dev 

And sorry for delayed response. Hm. Looking at the code, it should be fine. Is this always reproducible to you? Is there a way maybe to create dummy app where you can reproduce this and send it to us?

**Comment by BendingBender** [comment] 2020-10-07 10:32
Hi,

same here, crashes on every try with just the example code.

Xcode 12.0.1
iOS 14.0

**Comment by BendingBender** [comment] 2020-10-07 10:44
Ok, I think I've found the cause:
```
[55568:867207] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSUserTrackingUsageDescription key with a string value explaining to the user how the app uses this data.
```

**Comment by ugi** [comment] 2020-10-07 11:46
Hey guys,

Oh. Well, right. :) What @BendingBender pretty much explains the reason. Once API for showing consent dialog is invoked, iOS assumes that you have added text you wanna see displayed in `Info.plist` under that key. So simply add this to your native iOS Xcode project and things should work.

Let us know if that helped.

Cheers

**Comment by BendingBender** [comment] 2020-10-07 11:47
I've tested it, it worked after adding the key. Would be gread if you'd extend the docs to include this info.

**Comment by ugi** [comment] 2020-10-07 11:50
We were kinda under assumption that people might be aware of these things, but probably not the wisest assumption outside of native app development since dealing with native projects is not something most of people do in some serious manner. Fair point, will be added. Closing this one and in case there's need, feel free to comment/reopen.

And thank you one more time for figuring this out!

Cheers

**Closed by ugi** 2020-10-07 11:50 UTC
